# An explicit Python interpreter must not inherit the convenience dependency tree.
script <- sub('^--file=','',commandArgs()[grepl('^--file=',commandArgs())][1])
repo <- normalizePath(file.path(dirname(script),'..'))
source(file.path(repo,'functions/R/entrypoint.R'))
scratch <- file.path(repo,'.local/tmp');dir.create(scratch,recursive=TRUE,showWarnings=FALSE)
fake <- tempfile('entrypoint-',tmpdir=scratch);dir.create(fake)
dir.create(file.path(fake,'.local/python_deps'),recursive=TRUE)
dir.create(file.path(fake,'functions/python'),recursive=TRUE)
jsonlite::write_json(list(python='/bin/sh',rscript='/bin/true'),file.path(fake,'.local/runtime.json'))
record <- file.path(fake,'observed.txt')
writeLines(paste('printf "%s\\n" "$PYTHONPATH" >',shQuote(record)),file.path(fake,'functions/python/run.py'))
keys <- c('PANGLIOMA_PYTHON','PYTHONPATH','PYTHONDONTWRITEBYTECODE')
old <- Sys.getenv(keys,unset=NA_character_)
tryCatch({
 Sys.setenv(PYTHONPATH='caller-supplied-path',PANGLIOMA_PYTHON='/bin/sh')
 run_reproduction(fake)
 stopifnot(identical(readLines(record),'caller-supplied-path'))
 stopifnot(identical(Sys.getenv('PYTHONPATH'),'caller-supplied-path'))
 message('Explicit Python isolation: PASS')
 Sys.unsetenv('PANGLIOMA_PYTHON')
 run_reproduction(fake)
 expected <- paste(file.path(fake,'.local/python_deps'),'caller-supplied-path',sep=.Platform$path.sep)
 stopifnot(identical(readLines(record),expected))
 stopifnot(identical(Sys.getenv('PYTHONPATH'),'caller-supplied-path'))
 message('Default convenience runtime and environment restoration: PASS')
},finally={
 for(k in keys)if(is.na(old[[k]]))Sys.unsetenv(k)else do.call(Sys.setenv,setNames(list(old[[k]]),k))
 unlink(fake,recursive=TRUE)
})
